apiVersion: v1
kind: Secret
metadata:
  name: cluster-in-cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: in-cluster
  server: https://kubernetes.default.svc
  namespaces: argocd
  clusterResources: 'true'
  config: |
    {
      "tlsClientConfig": {
        "insecure": true,
        "certData": "<REDACTED>",
        "keyData": "<REDACTED>"
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-dev-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: dev
    fake-ns: dev
type: Opaque
stringData:
  name: dev
  server: https://kubernetes.default.svc
  namespaces: dev
  config: |
    {
      "tlsClientConfig": {
        "insecure": true,
        "certData": "<REDACTED>",
        "keyData": "<REDACTED>"
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-staging-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: staging
    fake-ns: staging
type: Opaque
stringData:
  name: staging
  server: https://kubernetes.default.svc
  namespaces: staging
  config: |
    {
      "tlsClientConfig": {
        "insecure": true,
        "certData": "<REDACTED>",
        "keyData": "<REDACTED>"
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-prod-1-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: prod
    fake-ns: production-1
type: Opaque
stringData:
  name: production-1
  server: https://kubernetes.default.svc
  namespaces: production-1
  config: |
    {
      "tlsClientConfig": {
        "insecure": true,
        "certData": "<REDACTED>",
        "keyData": "<REDACTED>"
      }
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-prod-2-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: prod
    fake-ns: production-2
type: Opaque
stringData:
  name: production-2
  server: https://kubernetes.default.svc
  namespaces: production-2
  config: |
    {
      "tlsClientConfig": {
        "insecure": true,
        "certData": "<REDACTED>",
        "keyData": "<REDACTED>"
      }
    }
