apiVersion: v1
kind: Service
metadata:
  name: dev
spec:
  type: ExternalName
  externalName: kubernetes.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: staging
spec:
  type: ExternalName
  externalName: kubernetes.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: production-1
spec:
  type: ExternalName
  externalName: kubernetes.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: production-2
spec:
  type: ExternalName
  externalName: kubernetes.default.svc.cluster.local

