apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/argoproj/argo-cd//manifests/cluster-install/?ref=master

patchesStrategicMerge:
  - ./patch/config/argocd-cm.yaml
  - ./patch/config/argocd-cmd-params-cm.yaml
  - ./patch/config/argocd-rbac-cm.yaml
